# Generated by Django 4.1.3 on 2022-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_drf', '0005_alter_customer_mobile_number_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
