# Generated by Django 4.1.3 on 2022-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_drf', '0006_alter_vendor_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
