# Generated by Django 4.1.3 on 2022-11-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_drf', '0007_sales_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='Eshop_drf.product'),
        ),
    ]
