# Generated by Django 4.1.3 on 2022-11-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_drf', '0008_alter_purchase_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
    ]
