# Generated by Django 4.1.3 on 2022-11-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_drf', '0009_rename_product_id_purchase_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='total_price',
        ),
    ]
