# Generated by Django 4.1.3 on 2022-11-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop_drf', '0010_remove_sales_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
